/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v{{VERSION}}
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as shared from "./../shared";
export interface IInvalidOperation {
    whatOp?: number;
    why?: string;
}
export interface IInvalidOperationArgs {
    whatOp?: number;
    why?: string;
}
export interface IInvalidResult {
    message?: string;
    code?: shared.ICode;
}
export interface IInvalidResultArgs {
    message?: string;
    code?: shared.ICodeArgs;
}
