/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v{{VERSION}}
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "test-lib";
import * as shared from "./../shared";
import * as common from "./../common";
import * as operation from "./../operation";
import * as __NAMESPACE__ from "./.";
export import ICommonStruct = common.ICommonStruct;
export import ICommonStructArgs = common.ICommonStructArgs;
export import CommonStruct = common.CommonStruct;
export import CommonStructCodec = common.CommonStructCodec;
