/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v{{VERSION}}
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "test-lib";
import * as shared from "./../shared";
import * as common from "./../common";
import * as operation from "./../operation";
export * from "./MyInteger";
export * from "./Operation";
export * from "./CommonStruct";
export * from "./INT32CONSTANT";
export * from "./MAPCONSTANT";
export * from "./Work";
export * from "./FirstName";
export * from "./LastName";
export * from "./Choice";
import * as Calculator from "./Calculator";
export { Calculator as Calculator };
