/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v2.0.11
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export const SHARED_INT: number = 45;
export interface ICode {
    status?: number;
}
export interface ICodeArgs {
    status?: number;
}
export interface ISharedStruct {
    code: ICode;
    value: string;
}
export interface ISharedStructArgs {
    code: ICodeArgs;
    value: string;
}
export interface ISharedUnion {
    option1?: string;
    option2?: string;
}
export interface ISharedUnionArgs {
    option1?: string;
    option2?: string;
}
