/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v2.0.11
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as common from "./../common";
import * as operation from "./../operation";
export type MyInteger = number;
export import Operation = operation.Operation;
export import ICommonStruct = common.ICommonStruct;
export import ICommonStructArgs = common.ICommonStructArgs;
export const INT32CONSTANT: number = 9853;
export const MAPCONSTANT: Map<string, string> = new Map([["hello", "world"], ["goodnight", "moon"]]);
export interface IWork {
    num1: number;
    num2: number;
    op: Operation;
    comment?: string;
}
export interface IWorkArgs {
    num1?: number;
    num2: number;
    op: Operation;
    comment?: string;
}
export interface IFirstName {
    name?: string;
}
export interface IFirstNameArgs {
    name?: string;
}
export interface ILastName {
    name?: string;
}
export interface ILastNameArgs {
    name?: string;
}
export interface IChoice {
    firstName?: IFirstName;
    lastName?: ILastName;
}
export interface IChoiceArgs {
    firstName?: IFirstNameArgs;
    lastName?: ILastNameArgs;
}
