/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v{{VERSION}}
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as __ROOT_NAMESPACE__ from "./../../..";
export type ICommonStruct = __ROOT_NAMESPACE__.ISharedStruct;
export type ICommonStructArgs = __ROOT_NAMESPACE__.ISharedStructArgs;
export const CommonStruct = __ROOT_NAMESPACE__.SharedStruct;
export const CommonStructCodec = __ROOT_NAMESPACE__.SharedStructCodec;
