/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v{{VERSION}}
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as __ROOT_NAMESPACE__ from "./../../..";
export const CommonEnum = __ROOT_NAMESPACE__.SharedEnum;
export type CommonEnum = __ROOT_NAMESPACE__.SharedEnum;
