/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v{{VERSION}}
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as __ROOT_NAMESPACE__ from "./../../..";
export type CommonUnionType = __ROOT_NAMESPACE__.SharedUnionType;
export type CommonUnion = __ROOT_NAMESPACE__.SharedUnion;
export type ICommonUnionWithOption1 = __ROOT_NAMESPACE__.ISharedUnionWithOption1;
export type ICommonUnionWithOption2 = __ROOT_NAMESPACE__.ISharedUnionWithOption2;
export type CommonUnionArgs = __ROOT_NAMESPACE__.SharedUnionArgs;
export type ICommonUnionWithOption1Args = __ROOT_NAMESPACE__.ISharedUnionWithOption1Args;
export type ICommonUnionWithOption2Args = __ROOT_NAMESPACE__.ISharedUnionWithOption2Args;
export const CommonUnionCodec = __ROOT_NAMESPACE__.SharedUnionCodec;
