/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v{{VERSION}}
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as __ROOT_NAMESPACE__ from "./../../..";
export const EnumKeyMap: Map<__ROOT_NAMESPACE__.SharedEnum, string> = new Map([[__ROOT_NAMESPACE__.SharedEnum.value1, "value1"], [__ROOT_NAMESPACE__.SharedEnum.value2, "value2"]]);
