/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v{{VERSION}}
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as OtherCommonUnion from "./OtherCommonUnion";
export type MoreOptionsType = OtherCommonUnion.OtherCommonUnionType;
export type MoreOptions = OtherCommonUnion.OtherCommonUnion;
export type IMoreOptionsWithOption1 = OtherCommonUnion.IOtherCommonUnionWithOption1;
export type IMoreOptionsWithOption2 = OtherCommonUnion.IOtherCommonUnionWithOption2;
export type MoreOptionsArgs = OtherCommonUnion.OtherCommonUnionArgs;
export type IMoreOptionsWithOption1Args = OtherCommonUnion.IOtherCommonUnionWithOption1Args;
export type IMoreOptionsWithOption2Args = OtherCommonUnion.IOtherCommonUnionWithOption2Args;
export const MoreOptionsCodec = OtherCommonUnion.OtherCommonUnionCodec;
