/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v{{VERSION}}
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as __ROOT_NAMESPACE__ from "./../../..";
import * as __NAMESPACE__ from "./.";
export type ICommonStruct = __ROOT_NAMESPACE__.ISharedStruct;
export type ICommonStructArgs = __ROOT_NAMESPACE__.ISharedStructArgs;
export const CommonStruct = __ROOT_NAMESPACE__.SharedStruct;
export const CommonStructCodec = __ROOT_NAMESPACE__.SharedStructCodec;
export type CommonUnionType = __ROOT_NAMESPACE__.SharedUnionType;
export type CommonUnion = __ROOT_NAMESPACE__.SharedUnion;
export type ICommonUnionWithOption1 = __ROOT_NAMESPACE__.ISharedUnionWithOption1;
export type ICommonUnionWithOption2 = __ROOT_NAMESPACE__.ISharedUnionWithOption2;
export type CommonUnionArgs = __ROOT_NAMESPACE__.SharedUnionArgs;
export type ICommonUnionWithOption1Args = __ROOT_NAMESPACE__.ISharedUnionWithOption1Args;
export type ICommonUnionWithOption2Args = __ROOT_NAMESPACE__.ISharedUnionWithOption2Args;
export const CommonUnionCodec = __ROOT_NAMESPACE__.SharedUnionCodec;
export const CommonEnum = __ROOT_NAMESPACE__.SharedEnum;
export type CommonEnum = __ROOT_NAMESPACE__.SharedEnum;
export const COMMON_INT = __ROOT_NAMESPACE__.SHARED_INT;
export type INotAllowed = __NAMESPACE__.IAuthException;
export type INotAllowedArgs = __NAMESPACE__.IAuthExceptionArgs;
export const NotAllowed = __NAMESPACE__.AuthException;
export const NotAllowedCodec = __NAMESPACE__.AuthExceptionCodec;
export type MoreOptionsType = __NAMESPACE__.OtherCommonUnionType;
export type MoreOptions = __NAMESPACE__.OtherCommonUnion;
export type IMoreOptionsWithOption1 = __NAMESPACE__.IOtherCommonUnionWithOption1;
export type IMoreOptionsWithOption2 = __NAMESPACE__.IOtherCommonUnionWithOption2;
export type MoreOptionsArgs = __NAMESPACE__.OtherCommonUnionArgs;
export type IMoreOptionsWithOption1Args = __NAMESPACE__.IOtherCommonUnionWithOption1Args;
export type IMoreOptionsWithOption2Args = __NAMESPACE__.IOtherCommonUnionWithOption2Args;
export const MoreOptionsCodec = __NAMESPACE__.OtherCommonUnionCodec;
