/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v{{VERSION}}
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as com_test_shared from "./../shared";
import * as __NAMESPACE__ from "./.";
export type ICommonStruct = com_test_shared.ISharedStruct;
export type ICommonStructArgs = com_test_shared.ISharedStructArgs;
export const CommonStruct = com_test_shared.SharedStruct;
export const CommonStructCodec = com_test_shared.SharedStructCodec;
export type CommonUnionType = com_test_shared.SharedUnionType;
export type CommonUnion = com_test_shared.SharedUnion;
export type ICommonUnionWithOption1 = com_test_shared.ISharedUnionWithOption1;
export type ICommonUnionWithOption2 = com_test_shared.ISharedUnionWithOption2;
export type CommonUnionArgs = com_test_shared.SharedUnionArgs;
export type ICommonUnionWithOption1Args = com_test_shared.ISharedUnionWithOption1Args;
export type ICommonUnionWithOption2Args = com_test_shared.ISharedUnionWithOption2Args;
export const CommonUnionCodec = com_test_shared.SharedUnionCodec;
export const CommonEnum = com_test_shared.SharedEnum;
export type CommonEnum = com_test_shared.SharedEnum;
export const COMMON_INT = com_test_shared.SHARED_INT;
export type INotAllowed = __NAMESPACE__.IAuthException;
export type INotAllowedArgs = __NAMESPACE__.IAuthExceptionArgs;
export const NotAllowed = __NAMESPACE__.AuthException;
export const NotAllowedCodec = __NAMESPACE__.AuthExceptionCodec;
export type MoreOptionsType = __NAMESPACE__.OtherCommonUnionType;
export type MoreOptions = __NAMESPACE__.OtherCommonUnion;
export type IMoreOptionsWithOption1 = __NAMESPACE__.IOtherCommonUnionWithOption1;
export type IMoreOptionsWithOption2 = __NAMESPACE__.IOtherCommonUnionWithOption2;
export type MoreOptionsArgs = __NAMESPACE__.OtherCommonUnionArgs;
export type IMoreOptionsWithOption1Args = __NAMESPACE__.IOtherCommonUnionWithOption1Args;
export type IMoreOptionsWithOption2Args = __NAMESPACE__.IOtherCommonUnionWithOption2Args;
export const MoreOptionsCodec = __NAMESPACE__.OtherCommonUnionCodec;
