/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v{{VERSION}}
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as shared from "./../shared";
export import ICommonStruct = shared.ISharedStruct;
export import ICommonStructArgs = shared.ISharedStructArgs;
export import ICommonUnion = shared.ISharedUnion;
export import ICommonUnionArgs = shared.ISharedUnionArgs;
export import COMMON_INT = shared.SHARED_INT;
export interface IAuthException {
    code?: number;
    message?: string;
}
export interface IAuthExceptionArgs {
    code?: number;
    message?: string;
}
