/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v{{VERSION}}
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as operation from "./../operation";
export const ENUM_CONST: Map<string, operation.Response> = new Map([["id", 32]]);
