import * as ts from 'typescript'
const pkg = require('../../package.json')

const prefaceComment: string =`
 * tslint:disable
 *
 * Autogenerated by @creditkarma/thrift-typescript v${pkg.version}
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
`

function generatePreface(req: ts.Statement): void {
  ts.addSyntheticLeadingComment(req,
    ts.SyntaxKind.MultiLineCommentTrivia,
    prefaceComment,
    true
  )
}

export function print(statements: Array<ts.Statement>): string {
  const printer: ts.Printer = ts.createPrinter()
  const rawSourceFile: ts.SourceFile = ts.createSourceFile(
    'thrift.ts',
    '',
    ts.ScriptTarget.ES2015,
    false,
    ts.ScriptKind.TS,
  )
  const bodyFile: ts.SourceFile = ts.updateSourceFileNode(rawSourceFile, statements)
  generatePreface(statements[0]);
  return printer.printBundle(ts.createBundle([ bodyFile ]))
}
