/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.1.1
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "test-lib";
export * from "./SHARED_INT";
export * from "./Code";
export * from "./SharedStruct";
export * from "./SharedUnion";
import * as SharedService from "./SharedService";
export { SharedService as SharedService };
