import * as ts from 'typescript'
const thriftParser = require('thrift-parser');

import readFile from './filesystem/read-file';

import {
  IDLNode,
  resolveIDLs
} from './resolve/idls';

import { identifiers as _id } from './ast/identifiers';

export function parseFile(fileName: string): Promise<any> {
  return readFile(fileName).then(idl => {
    return thriftParser(idl)
  })
}

function generateModuleFile(idl: IDLNode) {
  let bodyFile = ts.createSourceFile(`${idl.filename}.ts`, '', ts.ScriptTarget.ES5, false, ts.ScriptKind.TS);
  bodyFile = ts.updateSourceFileNode(bodyFile, [idl.toAST()]);

  return bodyFile;
}

function generatePreface() {
  let prefaceFile = ts.createSourceFile('preface.ts', '', ts.ScriptTarget.ES5, false, ts.ScriptKind.TS);

  const _thriftImport = ts.createImportClause(undefined, ts.createNamedImports([
    ts.createImportSpecifier(undefined, _id.Thrift)
  ]));
  let _require = ts.createImportDeclaration(undefined, undefined, _thriftImport, ts.createLiteral('thrift'));

  _require = ts.addSyntheticLeadingComment(_require, ts.SyntaxKind.SingleLineCommentTrivia, '', false);
  _require = ts.addSyntheticLeadingComment(_require, ts.SyntaxKind.SingleLineCommentTrivia, ' Autogenerated by thrift-typescript', false);
  _require = ts.addSyntheticLeadingComment(_require, ts.SyntaxKind.SingleLineCommentTrivia, '', false);
  _require = ts.addSyntheticLeadingComment(_require, ts.SyntaxKind.SingleLineCommentTrivia, ' DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING', false);
  _require = ts.addSyntheticLeadingComment(_require, ts.SyntaxKind.SingleLineCommentTrivia, '', true);

  prefaceFile = ts.updateSourceFileNode(prefaceFile, [
    _require
  ]);

  return prefaceFile;
}

function generateTypescript(files: ts.SourceFile[]) {
  const printer = ts.createPrinter();

  return printer.printBundle(ts.createBundle(files));
}

export async function generateIDLTypes(filename: string): Promise<string> {
  let idl = await parseFile(filename);
  idl.filename = filename;

  const resolved = resolveIDLs([idl]).map(generateModuleFile);

  const files = [generatePreface()].concat(resolved);

  return generateTypescript(files);
}
