/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.3.4
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "test-lib";
import * as __NAMESPACE__ from "./.";
export enum ChoiceType {
    ChoiceWithFirstName = "firstName",
    ChoiceWithLastName = "lastName"
}
export type Choice = IChoiceWithFirstName | IChoiceWithLastName;
export interface IChoiceWithFirstName {
    __type: ChoiceType.ChoiceWithFirstName;
    firstName: __NAMESPACE__.IFirstName;
    lastName?: undefined;
}
export interface IChoiceWithLastName {
    __type: ChoiceType.ChoiceWithLastName;
    firstName?: undefined;
    lastName: __NAMESPACE__.ILastName;
}
export type ChoiceArgs = IChoiceWithFirstNameArgs | IChoiceWithLastNameArgs;
export interface IChoiceWithFirstNameArgs {
    firstName: __NAMESPACE__.IFirstNameArgs;
    lastName?: undefined;
}
export interface IChoiceWithLastNameArgs {
    firstName?: undefined;
    lastName: __NAMESPACE__.ILastNameArgs;
}
export const ChoiceCodec: thrift.IStructToolkit<ChoiceArgs, Choice> = {
    create(args: ChoiceArgs): Choice {
        let _fieldsSet: number = 0;
        let _returnValue: any = null;
        if (args.firstName != null) {
            _fieldsSet++;
            const value_1: __NAMESPACE__.IFirstName = new __NAMESPACE__.FirstName(args.firstName);
            _returnValue = { firstName: value_1 };
        }
        if (args.lastName != null) {
            _fieldsSet++;
            const value_2: __NAMESPACE__.ILastName = new __NAMESPACE__.LastName(args.lastName);
            _returnValue = { lastName: value_2 };
        }
        if (_fieldsSet > 1) {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.INVALID_DATA, "TUnion cannot have more than one value");
        }
        else if (_fieldsSet < 1) {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.INVALID_DATA, "TUnion must have one value set");
        }
        if (_returnValue !== null) {
            if (_returnValue.firstName) {
                return {
                    __type: ChoiceType.ChoiceWithFirstName,
                    firstName: _returnValue.firstName
                };
            }
            else {
                return {
                    __type: ChoiceType.ChoiceWithLastName,
                    lastName: _returnValue.lastName
                };
            }
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read data for TUnion");
        }
    },
    encode(args: ChoiceArgs, output: thrift.TProtocol): void {
        let _fieldsSet: number = 0;
        const obj = {
            firstName: args.firstName,
            lastName: args.lastName
        };
        output.writeStructBegin("Choice");
        if (obj.firstName != null) {
            _fieldsSet++;
            output.writeFieldBegin("firstName", thrift.TType.STRUCT, 1);
            __NAMESPACE__.FirstNameCodec.encode(obj.firstName, output);
            output.writeFieldEnd();
        }
        if (obj.lastName != null) {
            _fieldsSet++;
            output.writeFieldBegin("lastName", thrift.TType.STRUCT, 2);
            __NAMESPACE__.LastNameCodec.encode(obj.lastName, output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        if (_fieldsSet > 1) {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.INVALID_DATA, "TUnion cannot have more than one value");
        }
        else if (_fieldsSet < 1) {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.INVALID_DATA, "TUnion must have one value set");
        }
        return;
    },
    decode(input: thrift.TProtocol): Choice {
        let _fieldsSet: number = 0;
        let _returnValue: any = null;
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRUCT) {
                        _fieldsSet++;
                        const value_3: __NAMESPACE__.IFirstName = __NAMESPACE__.FirstNameCodec.decode(input);
                        _returnValue = { firstName: value_3 };
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRUCT) {
                        _fieldsSet++;
                        const value_4: __NAMESPACE__.ILastName = __NAMESPACE__.LastNameCodec.decode(input);
                        _returnValue = { lastName: value_4 };
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_fieldsSet > 1) {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.INVALID_DATA, "TUnion cannot have more than one value");
        }
        else if (_fieldsSet < 1) {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.INVALID_DATA, "TUnion must have one value set");
        }
        if (_returnValue !== null) {
            if (_returnValue.firstName) {
                return {
                    __type: ChoiceType.ChoiceWithFirstName,
                    firstName: _returnValue.firstName
                };
            }
            else {
                return {
                    __type: ChoiceType.ChoiceWithLastName,
                    lastName: _returnValue.lastName
                };
            }
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read data for TUnion");
        }
    }
};
