/* tslint:disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.3.4
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as com_test_operation from "./../operation";
import * as com_test_common from "./../common";
export type MyInteger = number;
export import Operation = com_test_operation.Operation;
export import ICommonStruct = com_test_common.ICommonStruct;
export import ICommonStructArgs = com_test_common.ICommonStructArgs;
export import CommonStruct = com_test_common.CommonStruct;
export import CommonStructCodec = com_test_common.CommonStructCodec;
